from .administrador import router
from .afazer import router
from .professor import router
from .idioma import router
from .aluno import router
from .aula import router
from .login import router
from .carteira import router
from .conta_receber import router
from .conta_pagar import router