"""Tabela aulas adicionadas

Revision ID: 6aa16342f6e4
Revises: 7dd40668838f
Create Date: 2025-10-05 13:12:56.156118

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '6aa16342f6e4'
down_revision: Union[str, Sequence[str], None] = '7dd40668838f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('aulas',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('professor_id', sa.Integer(), nullable=False),
    sa.Column('data_aula', sa.DateTime(), nullable=False),
    sa.Column('idioma', sa.String(), nullable=False),
    sa.Column('valor_professor', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('valor_escola', sa.Numeric(precision=4, scale=2), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=True),
    sa.Column('repetir_dia', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['professor_id'], ['professores.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_aulas_id'), 'aulas', ['id'], unique=False)
    op.create_table('aula_aluno',
    sa.Column('aula_id', sa.Integer(), nullable=False),
    sa.Column('aluno_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['aluno_id'], ['alunos.id'], ),
    sa.ForeignKeyConstraint(['aula_id'], ['aulas.id'], ),
    sa.PrimaryKeyConstraint('aula_id', 'aluno_id')
    )
    op.drop_column('idiomas', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idiomas', sa.Column('nome', mysql.VARCHAR(length=40), nullable=False))
    op.drop_table('aula_aluno')
    op.drop_index(op.f('ix_aulas_id'), table_name='aulas')
    op.drop_table('aulas')
    # ### end Alembic commands ###
