"""Renomeia coluna Pais para pais na tabela alunos

Revision ID: 7dd40668838f
Revises: 1a1e7705b00b
Create Date: 2025-10-05 10:54:16.632176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7dd40668838f'
down_revision: Union[str, Sequence[str], None] = '1a1e7705b00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


"""Renomeia coluna Pais para pais na tabela alunos

Revision ID: 7dd40668838f
Revises: 1a1e7705b00b
Create Date: 2025-10-05 10:54:16.632176

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '7dd40668838f'
down_revision: Union[str, Sequence[str], None] = '1a1e7705b00b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alunos', 'Pais', new_column_name='pais', existing_type=sa.String(100))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('alunos', 'pais', new_column_name='Pais', existing_type=sa.String(100))
    # ### end Alembic commands ###
