"""adicionar_tabela_idiomas

Revision ID: abf0c8b93b45
Revises: ae1f290b5cd5
Create Date: 2025-10-01 20:39:34.896117

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = 'abf0c8b93b45'
down_revision: Union[str, Sequence[str], None] = 'ae1f290b5cd5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idiomas', sa.Column('nome_idioma', sa.String(length=40), nullable=False))
    op.drop_index(op.f('nome'), table_name='idiomas')
    op.create_unique_constraint(None, 'idiomas', ['nome_idioma'])
    op.drop_column('idiomas', 'nome')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idiomas', sa.Column('nome', mysql.VARCHAR(length=40), nullable=False))
    op.drop_constraint(None, 'idiomas', type_='unique')
    op.create_index(op.f('nome'), 'idiomas', ['nome'], unique=True)
    op.drop_column('idiomas', 'nome_idioma')
    # ### end Alembic commands ###
